apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradlew-test-task
spec:
  resources:
    inputs:
      - name: workspace
        type: git
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
